services:
    memcached:
        class: Memcached
        calls:
            - [addServers, ["%memcached_servers%"]]

    doctrine.cache.driver.memcached:
        class: bigpaulie\CacheBundle\Drivers\Memcached
        calls:
            - [setMemcached, ["@memcached"]]
            - [parseNamespace]
